lab 5
igorv404/flutter-first-app pull request #5
Opened 2024-04-04 10:57 UTC by igorv404

2024-04-04 19:36 UTC, DenysDoskochynskyi requested changes

2024-04-04 19:36 UTC, DenysDoskochynskyi commented on lib/repositories/establishment_repository.dart
> +class EstablishmentRepository {
add abstraction usage)

2024-04-04 19:36 UTC, DenysDoskochynskyi commented on lib/services/user_service.dart
> +class UserService {
provide abstraction & extract api url as a const

2024-04-05 07:41 UTC, igorv404 commented on lib/repositories/establishment_repository.dart
> +class EstablishmentRepository {
Done

2024-04-05 07:41 UTC, igorv404 commented on lib/services/user_service.dart
> +class UserService {
Done

2024-04-06 17:01 UTC, merged